spring.application.name=pixel-board

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/pixelboard
spring.datasource.username=pixel
spring.datasource.password=pixel123
spring.jpa.hibernate.ddl-auto=validate

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=pixel-board-group
spring.kafka.consumer.auto-offset-reset=earliest

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379